export default {
  USERS_FETCH: 'USERS_FETCH',
  USERS_FETCH_SUCCESS: 'USERS_FETCH_SUCCESS',
  USERS_FETCH_ERROR: 'USERS_FETCH_ERROR',
  USERS_SAVE: 'USERS_SAVE',
  USERS_SAVE_SUCCESS: 'USERS_SAVE_SUCCESS',
  USERS_SAVE_ERROR: 'USERS_SAVE_ERROR',
}